version: 2

project_name: muxic

builds:
  - id: muxic
    main: ./main.go
    binary: muxic
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X muxic/cmd.Version={{.Tag}}

archives:
  - id: default
    ids:
      - muxic
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

nfpms:
  - id: muxic-deb
    package_name: muxic
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Arch }}"
    ids:
      - muxic
    formats:
      - deb
    bindir: /usr/bin
    vendor: Punk Science Studios Inc
    homepage: https://github.com/punkscience/muxic
    maintainer: Darryl Wright <darryl@punkscience.ca>
    description: Opinionated CLI utility to organize music by metadata.
    license: Unlicense
    section: utils
    priority: optional

brews:
  - name: muxic
    ids:
      - muxic
    repository:
      owner: punkscience
      name: homebrew-muxic
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/punkscience/muxic
    description: Opinionated CLI utility to organize music by metadata.
    license: Unlicense
    test: |
      system "#{bin}/muxic --help"

release:
  github:
    owner: punkscience
    name: muxic
